version: '3.5'
services:
  catalogService:
    image: catalog:v1
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    environment:
      - "CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=mysql,3306;Database=catalog;User=user;Password=password"
    ports:
      - "5001:8080"
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'catalog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33060:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: